default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: speedmsg_development

test:
  <<: *default
  database: speedmsg_test

production:
  <<: *default
  database: speedmsg_production
  username: speedmsg
  password: <%= ENV['SPEEDMSG_DATABASE_PASSWORD'] %>
